version: '3.8'

networks:
  nats-net:
    name: nats

services: 
  nats:
    image: nats
    container_name: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: 
      - nats-net
  nats-1:
    image: nats
    ports:
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: 
      - nats-net
    depends_on: 
      - nats
  nats-2:
    image: nats
    ports:
      - "4223:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: 
      - nats-net
    depends_on: 
      - nats

